app:
  doc:
    version: 2023-Spring
    title: SE352-452 Video Game Account API3
    description: This is a documentation for the video game account service.
    terms-of-service: http://swagger.io/terms/
    license:  Apache 2.0
    url: http://springdoc.org

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true

spring:
  profiles:
    active: dev