#Be sure to change volumn location
#start:   docker-compose up -d
#stop:    docker-compose down

version: '3.8'

services:
    app:
        container_name: project
        image: voporak5/se452-group-6:latest
        env_file: ./.env
        ports:
            - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
        